version: '3'
services:
  app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
    user: node
    working_dir: "/app"
    command: ash -c "npm install && npm run gulp"